# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  lotteryapi:
    image: lotteryapi
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lotteryapi
    environment:
      VIRTUAL_HOST: lottery.ginjs.click
      LETSENCRYPT_HOST: lottery.ginjs.click
    restart: always
    networks:
      - proxy

networks:
 proxy:
    name: nginx-network
    external: true
